# Generated by Django 2.0.5 on 2018-06-18 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(default='', max_length=20)),
                ('courseName', models.CharField(default='', max_length=100)),
                ('totalFiles', models.BigIntegerField(default=0)),
                ('semester', models.CharField(default='', max_length=2)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptName', models.CharField(default='', max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('courseType', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaperUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='papers/')),
                ('filename', models.CharField(default='', max_length=100)),
                ('uploadEmail', models.CharField(default='', max_length=100)),
                ('uploadDate', models.DateTimeField(default=datetime.datetime(2018, 6, 18, 18, 8, 12, 97115, tzinfo=utc))),
                ('numLikes', models.BigIntegerField(default=0)),
                ('numDislikes', models.BigIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbase.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbase.Department'),
        ),
    ]
