# Generated by Django 2.0.5 on 2018-06-19 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='semesterCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paperupload',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 13, 28, 31, 100396, tzinfo=utc)),
        ),
    ]
