# Generated by Django 2.0.5 on 2018-06-19 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainbase', '0002_auto_20180619_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paperupload',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 13, 53, 46, 918320, tzinfo=utc)),
        ),
    ]
