# Generated by Django 2.0.5 on 2018-06-21 15:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainbase', '0003_auto_20180619_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperupload',
            name='uploadEmail',
        ),
        migrations.AddField(
            model_name='paperupload',
            name='uploadUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paperupload',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 15, 6, 41, 37464, tzinfo=utc)),
        ),
    ]
