# Generated by Django 2.0.5 on 2018-06-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbase', '0004_auto_20180621_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paperupload',
            name='uploadDate',
        ),
        migrations.AddField(
            model_name='paperupload',
            name='examDate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseID',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
