# Generated by Django 2.0.5 on 2018-06-23 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbase', '0005_auto_20180623_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperupload',
            name='uploadUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
